// <auto-generated />
using System;
using FistApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FistApi.Migrations
{
    [DbContext(typeof(FistApiContext))]
    partial class FistApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FistApi.Models.Profil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LabelAr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Profils");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "Administrateur",
                            LabelAr = "مدير"
                        },
                        new
                        {
                            Id = 2,
                            Label = "Superviseur",
                            LabelAr = "مشرف"
                        },
                        new
                        {
                            Id = 3,
                            Label = "Point focal",
                            LabelAr = "	المخاطب الرئيسي"
                        },
                        new
                        {
                            Id = 4,
                            Label = "Propriétaire",
                            LabelAr = "مالك"
                        });
                });

            modelBuilder.Entity("FistApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("IdProfil")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdProfil");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresse = "Temara",
                            Email = "mourabit@angular.io",
                            IdProfil = 1,
                            Nom = "mourabit",
                            Password = "123",
                            Prenom = "mohamed",
                            Username = "mourabit"
                        },
                        new
                        {
                            Id = 2,
                            Adresse = "Temara",
                            Email = "mehdi@angular.io",
                            IdProfil = 2,
                            Nom = "mehdi",
                            Password = "123",
                            Prenom = "mehdi",
                            Username = "mehdi"
                        },
                        new
                        {
                            Id = 3,
                            Adresse = "Temara",
                            Email = "ahmed@angular.io",
                            IdProfil = 4,
                            Nom = "ahmed",
                            Password = "123",
                            Prenom = "ahmed",
                            Username = "ahmed"
                        },
                        new
                        {
                            Id = 4,
                            Adresse = "Temara",
                            Email = "soufiane@angular.io",
                            IdProfil = 3,
                            Nom = "soufiane",
                            Password = "123",
                            Prenom = "soufiane",
                            Username = "soufiane"
                        });
                });

            modelBuilder.Entity("FistApi.Models.User", b =>
                {
                    b.HasOne("FistApi.Models.Profil", "Profil")
                        .WithMany("User")
                        .HasForeignKey("IdProfil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profil");
                });

            modelBuilder.Entity("FistApi.Models.Profil", b =>
                {
                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
